---

- name: Smokey Feet
  hosts: web

  environment:
    LC_ALL: 'en_US.UTF-8'

  pre_tasks:
    - name: Ensure apt cache updated
      become: yes
      apt:
        cache_valid_time: 86400
        update_cache: yes

  roles:
    - role: base
      become: yes

    - role: postgres
      become: yes

    - role: uwsgi
      become: yes

    - role: nginx
      become: yes

    - role: smokeyfeet
