---

- name: Smokey Feet
  hosts: web

  pre_tasks:
    - name: Ensure apt cache updated
      sudo: yes
      apt: update_cache=yes

  roles:
    - role: base
      sudo: yes

    - role: postgres
      sudo: yes

    - role: smokeyfeet
