---

- name: Smokey Feet
  hosts: web

  pre_tasks:
    - name: Ensure apt cache updated
      become: yes
      apt:
        cache_valid_time: 86400
        update_cache: yes

  roles:
    - role: base
      become: yes

    - role: postgres
      become: yes

    - role: smokeyfeet
