---

- name: Ensure django packages installed
  apt: pkg={{ item }}
  become: True
  with_items:
    - git
    - python3-pip
    - python3-psycopg2
    - python3-virtualenv
    - virtualenv

- name: Manually create the initial virtualenv
  command: "virtualenv {{ sf_venv_path }} -p /usr/bin/python3.4"

- name: Check out the repository
  git:
    repo: "{{ sf_reg_repo_url }}"
    dest: "{{ sf_proj_path }}"
    accept_hostkey: yes
    version: "{{ sf_register.git_version }}"
  notify: restart uwsgi

- name: Install pip packages from requirements.txt
  pip:
    requirements: "{{ sf_proj_path }}/requirements.txt"
    virtualenv: "{{ sf_venv_path }}"
  notify: restart uwsgi

- name: Ensure django config in place
  template:
    src: "settings.{{ sf_environment }}.py.j2"
    dest: "{{ sf_proj_path }}/smokeyfeet/settings.py"
    mode: 0644
  notify: restart uwsgi

- name: Apply migrations
  django_manage:
    command: migrate
    app_path: "{{ sf_proj_path }}"
    virtualenv: "{{ sf_venv_path }}"
  notify: restart uwsgi

- name: Collect static content
  django_manage:
    command: "collectstatic"
    app_path: "{{ sf_proj_path }}"
    virtualenv: "{{ sf_venv_path }}"
  notify: restart uwsgi

- name: Load default pass types
  django_manage:
    command: "loaddata {{ item }}"
    app_path: "{{ sf_proj_path }}"
    virtualenv: "{{ sf_venv_path }}"
  with_items:
    - competition_types
    - pass_types
    - volunteer_types
