---

- name: Ensure nginx packages installed
  become: True
  apt: pkg={{ item }}
  with_items:
    - nginx-common
    - nginx-full

## website

- name: Ensure nginx config in place
  become: True
  template:
    src: nginx-www.smokeyfeet.com.conf.j2
    dest: "/etc/nginx/sites-available/{{ sf_website.fqdn }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Ensure nginx config is enabled
  become: True
  file:
    src: "/etc/nginx/sites-available/{{ sf_website.fqdn }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ sf_website.fqdn }}.conf"
    owner: root
    group: root
    state: link
  notify: restart nginx

- name: Ensure website directory exists
  become: True
  file:
    path: "/var/www/{{ sf_website.fqdn }}"
    state: directory
    mode: 0755

## register

- name: Ensure nginx config in place
  become: True
  template:
    src: nginx-register.smokeyfeet.com.conf.j2
    dest: "/etc/nginx/sites-available/{{ sf_register.fqdn }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Ensure nginx config is enabled
  become: True
  file:
    src: "/etc/nginx/sites-available/{{ sf_register.fqdn }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ sf_register.fqdn }}.conf"
    owner: root
    group: root
    state: link
  notify: restart nginx
