---

- name: Ensure config in place
  become: True
  template:
    src: uwsgi-smokeyfeet.ini.j2
    dest: /etc/uwsgi/apps-available/smokeyfeet.ini
    owner: root
    group: root
    mode: 0644
  notify: restart uwsgi

- name: Enable through symlink
  become: True
  file:
    src: /etc/uwsgi/apps-available/smokeyfeet.ini
    path: /etc/uwsgi/apps-enabled/smokeyfeet.ini
    state: link
    owner: root
    group: root
    mode: 0644
  notify: restart uwsgi
